### PR TITLE
Add check to avoid common error when first connecting

### PR DESCRIPTION
**Pull request by alanning**
Heya, been seeing a "conn undefined" type error popping up a lot in our logs.  Just adding a quick sanity check...

### CODE REVIEW

**Comment by lorensr** [comment]
hah, i just tried to run `npm version patch` 😜

**Comment by alanning** [comment]
Hi Loren, could you publish a new version of this package with this fix, please?

**Comment by lorensr** [comment]
Sure, assumed you were just using local.

**Comment by alanning** [comment]
Yep, have been but I'd like to avoid that if possible.  :-)

**Comment by lorensr** [comment]
Thanks for the PR, included in `0.1.5` https://github.com/lorensr/roles-restricted/blob/master/CHANGELOG.md#015---2016-09-28

**Pull request merged**
